
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    constant_identifier_names: false
    public_member_api_docs: false
    prefer_mixin: false
    avoid_positional_boolean_parameters: false
    prefer_interpolation_to_compose_strings: false
    avoid_classes_with_only_static_members: false
    avoid_print: false
    sort_pub_dependencies: false
    use_named_constants: false
    lines_longer_than_80_chars: false
    always_use_package_imports: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
