name: test_metrics
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.13.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.3
  pretty_dio_logger: ^1.2.0-beta-1
  intl: ^0.17.0
  shared_preferences: ^2.0.9
  freezed_annotation: ^1.0.0
  json_annotation: ^4.3.0
  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
  cloud_firestore: ^3.1.0
  google_sign_in: ^5.2.1
  flutter_signin_button: ^2.0.0
  cached_network_image: ^3.1.0+1
  sensors_plus: ^1.2.1
  flutter_echarts: ^2.3.0
  firebase_analytics: ^9.0.4
  mask_text_input_formatter: ^2.0.0
  numberpicker: ^2.1.1
  flutter_svg: ^1.0.0
  flutter_uxcam: ^2.0.1
  shake_flutter: ^15.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.2.1
  flutter_launcher_icons: ^0.9.1
  lint: ^1.0.0
  build_runner: ^2.1.1
  json_serializable: ^6.0.1
  freezed: ^1.0.0
  # flutter pub run change_app_package_name:main com.test.metrics
  change_app_package_name: ^1.0.0


flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Heavy.ttf
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
  assets:
    - assets/images/
    - assets/splash/
    - assets/icon/
    - assets/svg/
    - lib/services/localization/langs/

# flutter pub pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/splash/splash.png
  android_gravity: fill_horizontal
  ios_content_mode: scaleAspectFill
  # color: "1C222A"
  background_image: "assets/splash/background.png"
  remove_alpha_ios: true

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/icon/icon.png